COMP: Updated ITK for c++11 required
Remove alias that is no longer needed.
error: static assertion failed: ERROR: ITK_NOEXCEPT must be replaced with 'noexcept'